[package]
name = "hello-ai-game"
version = "0.1.0"
edition = "2021"

[features]
# To build with kalosm's "cuda" feature, compile with `cargo build --features cuda --release`
# Host needs CUDA dev tools installed
cuda = ["kalosm/cuda"]
# To build with kalosm's "mkl" feature, compile with `cargo build --features mkl --release`
# Host needs intel-oneapi-mkl / Intel MKL dev tools installed
mkl = ["kalosm/mkl"]

[dependencies]
kalosm = { git = "https://github.com/floneum/floneum", version = "0.3", features = ["full"] }
tokio = { version = "1.41", features = ["full"] }

stablediffusion = { git = "https://github.com/Gadersd/stable-diffusion-burn", version = "0.1", features = [ ] }
downloader = "0.2"
image = "0.24"
burn = "0.14.0"
burn-ndarray = "0.14.0"
burn-tch = "0.14.0"
burn-autodiff = "0.14.0"
tch = "0.15.0"
rust_tokenizers = "8.1.0"


