[package]
name = "hello-ai-game"
version = "0.1.0"
edition = "2021"

[dependencies]
kalosm = { git = "https://github.com/floneum/floneum", version = "0.3", features = ["full"] }
tokio = { version = "1.41", features = ["full"] }


